---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kube.adrp.xyz/rendered: "true"
resources:
  - crds/cephblockpoolradosnamespaces.ceph.rook.io.yml
  - crds/cephblockpools.ceph.rook.io.yml
  - crds/cephbucketnotifications.ceph.rook.io.yml
  - crds/cephbuckettopics.ceph.rook.io.yml
  - crds/cephclients.ceph.rook.io.yml
  - crds/cephclusters.ceph.rook.io.yml
  - crds/cephconnections.csi.ceph.io.yml
  - crds/cephcosidrivers.ceph.rook.io.yml
  - crds/cephfilesystemmirrors.ceph.rook.io.yml
  - crds/cephfilesystems.ceph.rook.io.yml
  - crds/cephfilesystemsubvolumegroups.ceph.rook.io.yml
  - crds/cephnfses.ceph.rook.io.yml
  - crds/cephobjectrealms.ceph.rook.io.yml
  - crds/cephobjectstores.ceph.rook.io.yml
  - crds/cephobjectstoreusers.ceph.rook.io.yml
  - crds/cephobjectzonegroups.ceph.rook.io.yml
  - crds/cephobjectzones.ceph.rook.io.yml
  - crds/cephrbdmirrors.ceph.rook.io.yml
  - crds/clientprofilemappings.csi.ceph.io.yml
  - crds/clientprofiles.csi.ceph.io.yml
  - crds/drivers.csi.ceph.io.yml
  - crds/objectbucketclaims.objectbucket.io.yml
  - crds/objectbuckets.objectbucket.io.yml
  - crds/operatorconfigs.csi.ceph.io.yml
  - manifests/sa_objectstorage-provisioner.yml
  - manifests/sa_rook-ceph-cmd-reporter.yml
  - manifests/sa_rook-ceph-default.yml
  - manifests/sa_rook-ceph-mgr.yml
  - manifests/sa_rook-ceph-osd.yml
  - manifests/sa_rook-ceph-purge-osd.yml
  - manifests/sa_rook-ceph-rgw.yml
  - manifests/sa_rook-ceph-system.yml
  - manifests/sa_rook-csi-cephfs-plugin-sa.yml
  - manifests/sa_rook-csi-cephfs-provisioner-sa.yml
  - manifests/sa_rook-csi-rbd-plugin-sa.yml
  - manifests/sa_rook-csi-rbd-provisioner-sa.yml
  - manifests/sa_ceph-csi-cephfs-ctrlplugin-sa.yml
  - manifests/sa_ceph-csi-cephfs-nodeplugin-sa.yml
  - manifests/sa_ceph-csi-controller-manager.yml
  - manifests/sa_ceph-csi-nfs-ctrlplugin-sa.yml
  - manifests/sa_ceph-csi-nfs-nodeplugin-sa.yml
  - manifests/sa_ceph-csi-rbd-ctrlplugin-sa.yml
  - manifests/sa_ceph-csi-rbd-nodeplugin-sa.yml
  - manifests/r_cephfs-external-provisioner-cfg.yml
  - manifests/r_rbd-external-provisioner-cfg.yml
  - manifests/r_rook-ceph-cmd-reporter.yml
  - manifests/r_rook-ceph-mgr.yml
  - manifests/r_rook-ceph-osd.yml
  - manifests/r_rook-ceph-purge-osd.yml
  - manifests/r_rook-ceph-system.yml
  - manifests/r_ceph-csi-cephfs-ctrlplugin-r.yml
  - manifests/r_ceph-csi-cephfs-nodeplugin-r.yml
  - manifests/r_ceph-csi-leader-election-role.yml
  - manifests/r_ceph-csi-rbd-ctrlplugin-r.yml
  - manifests/r_ceph-csi-rbd-nodeplugin-r.yml
  - manifests/cr_ceph-csi-cephconnection-viewer-role.yml
  - manifests/cr_ceph-csi-cephconnections-editor-role.yml
  - manifests/cr_ceph-csi-cephfs-ctrlplugin-cr.yml
  - manifests/cr_ceph-csi-cephfs-nodeplugin-cr.yml
  - manifests/cr_ceph-csi-clientprofile-viewer-role.yml
  - manifests/cr_ceph-csi-clientprofilemapping-editor-role.yml
  - manifests/cr_ceph-csi-clientprofilemapping-viewer-role.yml
  - manifests/cr_ceph-csi-clientprofiles-editor-role.yml
  - manifests/cr_ceph-csi-driver-editor-role.yml
  - manifests/cr_ceph-csi-driver-viewer-role.yml
  - manifests/cr_ceph-csi-manager-role.yml
  - manifests/cr_ceph-csi-metrics-auth-role.yml
  - manifests/cr_ceph-csi-metrics-reader.yml
  - manifests/cr_ceph-csi-nfs-ctrlplugin-cr.yml
  - manifests/cr_ceph-csi-nfs-nodeplugin-cr.yml
  - manifests/cr_ceph-csi-operatorconfig-editor-role.yml
  - manifests/cr_ceph-csi-operatorconfig-viewer-role.yml
  - manifests/cr_ceph-csi-rbd-ctrlplugin-cr.yml
  - manifests/cr_ceph-csi-rbd-nodeplugin-cr.yml
  - manifests/cr_cephfs-csi-nodeplugin.yml
  - manifests/cr_cephfs-external-provisioner-runner.yml
  - manifests/cr_objectstorage-provisioner-role.yml
  - manifests/cr_rbd-csi-nodeplugin.yml
  - manifests/cr_rbd-external-provisioner-runner.yml
  - manifests/cr_rook-ceph-cluster-mgmt.yml
  - manifests/cr_rook-ceph-global.yml
  - manifests/cr_rook-ceph-mgr-cluster.yml
  - manifests/cr_rook-ceph-mgr-system.yml
  - manifests/cr_rook-ceph-object-bucket.yml
  - manifests/cr_rook-ceph-osd.yml
  - manifests/cr_rook-ceph-system.yml
  - manifests/rb_cephfs-csi-provisioner-role-cfg.yml
  - manifests/rb_rbd-csi-provisioner-role-cfg.yml
  - manifests/rb_rook-ceph-cluster-mgmt.yml
  - manifests/rb_rook-ceph-cmd-reporter.yml
  - manifests/rb_rook-ceph-mgr.yml
  - manifests/rb_rook-ceph-mgr-system.yml
  - manifests/rb_rook-ceph-osd.yml
  - manifests/rb_rook-ceph-purge-osd.yml
  - manifests/rb_rook-ceph-system.yml
  - manifests/rb_ceph-csi-cephfs-ctrlplugin-rb.yml
  - manifests/rb_ceph-csi-cephfs-nodeplugin-rb.yml
  - manifests/rb_ceph-csi-leader-election-rolebinding.yml
  - manifests/rb_ceph-csi-rbd-ctrlplugin-rb.yml
  - manifests/rb_ceph-csi-rbd-nodeplugin-rb.yml
  - manifests/crb_ceph-csi-cephfs-ctrlplugin-crb.yml
  - manifests/crb_ceph-csi-cephfs-nodeplugin-crb.yml
  - manifests/crb_ceph-csi-manager-rolebinding.yml
  - manifests/crb_ceph-csi-metrics-auth-rolebinding.yml
  - manifests/crb_ceph-csi-nfs-ctrlplugin-crb.yml
  - manifests/crb_ceph-csi-nfs-nodeplugin-crb.yml
  - manifests/crb_ceph-csi-rbd-ctrlplugin-crb.yml
  - manifests/crb_ceph-csi-rbd-nodeplugin-crb.yml
  - manifests/crb_cephfs-csi-nodeplugin-role.yml
  - manifests/crb_cephfs-csi-provisioner-role.yml
  - manifests/crb_objectstorage-provisioner-role-binding.yml
  - manifests/crb_rbd-csi-nodeplugin.yml
  - manifests/crb_rbd-csi-provisioner-role.yml
  - manifests/crb_rook-ceph-global.yml
  - manifests/crb_rook-ceph-mgr-cluster.yml
  - manifests/crb_rook-ceph-object-bucket.yml
  - manifests/crb_rook-ceph-osd.yml
  - manifests/crb_rook-ceph-system.yml
  - manifests/cm_rook-ceph-operator-config.yml
  - manifests/d_rook-ceph-operator.yml
  - manifests/d_ceph-csi-controller-manager.yml
