---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: rook-ceph
    namespace: rook-ceph
    repo: oci://ghcr.io/rook/
    valuesFile: values.yaml
    includeCRDs: true
    version: v1.18.7
