---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: external-secrets-1.0.0
  name: release-name-external-secrets-cert-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-external-secrets-cert-controller
subjects:
  - kind: ServiceAccount
    name: external-secrets-cert-controller
    namespace: external-secrets
