---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: external-secrets-1.0.0
  name: release-name-external-secrets
  namespace: external-secrets
