apiVersion: v1
imagePullSecrets:
  - name: private-registry
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
    app.kubernetes.io/part-of: container-object-storage-interface
  name: objectstorage-provisioner
  namespace: rook-ceph
