---
apiVersion: v1
imagePullSecrets:
  - name: private-registry
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/version: v1.18.7
    helm.sh/chart: rook-ceph-v1.18.7
    operator: rook
    storage-backend: ceph
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-ceph
