---
name: Auto-approve_Renovate

on:
  pull_request_target:
    branches:
      - main
  workflow_call:
  workflow_run:
    workflows:
      # work-flow name
      - Populate Renovate resources
      # job name
      - Update Resources
  push:
    branches:
      - "renovate/**"

permissions:
  pull-requests: write
  contents: write

jobs:
  renovate:
    name: renovate
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - uses: 8BitJonny/gh-get-current-pr@4056877062a1f3b624d5d4c2bedefa9cf51435c9 # v4.0.0
        id: PR

      - name: Approve a PR
        run: gh pr review --approve ${{ steps.PR.outputs.number }}
        if: ${{ github.event.pull_request.html_url != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
